---
output: pdf_document
---

Essential are the genes/proteins which are indispensable for the organism. Much research has focused on the identification of these genes/proteins because they are considered part of the *minimal gene set*, they are possible drug targets for pathogens and more knowledge about them will help for better therapeutic strategies for human diseases. The experimental procedures for the detection of essential genes are expensive, laborious and in most cases unfeasible. So scientists have created tools for their prediction from other data using computational approaches. The most important results have come from centrality indices in protein interaction networks which formed the *centrality - lethality rule*. According to *centrality - lethality rule* the higher the degree of a protein the more likely to be essential. Since it's introduction, this rule has been expanded to other centralities and many novel methods have been developed  that integrate a variety of data. Despite all these advancements, the underlying network has largely remained the same. For a better representation of protein interactions, additional information must be included to them like activation/inhibition, direction and type. In this work, we used the first large scale signed protein interaction network, which was constructed using protein interaction and RNAi screen data for *D.melanogaster*, to predict essential protein using centrality indices. 

**Keywords:** essential gene/protein, centrality lethality rule, signed protein networks, systems biology, protein complex
