---
bibliography: Networks Centralities and Negative Weigths.bib
output:
  pdf_document: default
  html_document: default
  word_document: default
header-includes:
- \usepackage{placeins}
- \usepackage{fancyhdr}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{graphicx}
- \usepackage{microtype}
- \onehalfspacing
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage[utf8]{inputenc}
- \usepackage[greek,english]{babel}
- \renewcommand{\familydefault}{\sfdefault}
- \usepackage{helvet}
- \usepackage{mathtools}
- \usepackage{amsmath}
- \usepackage{sansmathfonts}
- \newtheorem{theorem}{Theorem}
- \newtheorem{mydef}{Definition}
- \usepackage{multirow}
- \usepackage{subcaption}
---

# Discussion

In this study, we applied centrality indices to predict essential proteins in the signed protein interaction network of \textit{D.melanogaster}. We found that degree centrality had the best performance with $AUC=0.804$ and betweenness scored low with performance of $AUC=0.591$. Both methods performed better that degree, $AUC=0.435$, in the original PPI network of \textit{D.melanogaster}. Actually, the latter result suggest that the centrality - lethality rule is very weak in the PPI network of \textit{D.melanogaster}. To our knowledge, this result hasn't been made clear in literature. For example, in [@Peng2015a], the authors test the prediction power of their novel method and some centralities for essentiality consensus. They used the same network data from BioGRID [@Stark2006a] that we used. In Figure 6a of their manuscript they present the same results with ours. Their results indicate that the top 80 hub proteins contained only $5\%$ of essential proteins and the $25\%$ of proteins with the highest degree don't even contain $7.5\%$ of essential proteins. Their novel method also never surpasses the prediction of $10\%$ of the essential proteins of \textit{D.melanogaster}. These prediction results suggest that degree and the other centrality methods are poor predictors of essentiality and question the applicability of the centrality - lethality rule in the protein interaction networks of \textit{D.melanogaster}. 

The centrality - lethality rule has been extensively tested in more than 10 organisms, most of them unicellular [@Zhang2016d], and this weak performance in \textit{D.melanogaster's} PPI's hasn't been stated directly. There is a gap in the literature about \textit{D.melanogaster} and the centrality-lethality rule since most studies focus on \textit{S.cerevisiae}. Despite these limitations in the PPI network of \textit{D.melanogaster} we found that centralities are good predictors in the signed network. Further tests are needed to decipher the reasons of these differences between these networks. The success of centralities in the signed network may appear due to biases towards essential proteins since it is a sub-network of the PPI of \textit{D.melanogaster} by construction.

The best centrality measure for essential protein prediction is the local interaction density centrality (LIDC) which incorporates protein complex data and topological features [@Luo2015]. This finding further validates the general argument that the integration of diverse data provides better results. Apart from data integration, it is generally accepted that method integration provides better results that individual methods [@Cheng2014; @Zhang2016d]. In this study, the best results for the prediction of essential proteins were from the decision trees when applied on centralities. As seen in Figure \ref{fig_trees}, positive degree and weighted positive degree were used as decision rules to predict essential proteins. This is a property that characterizes essential proteins in the signed protein network of \textit{D.melanogaster} which hasn't been reported before. As new signed networks will be created in the future this property shall be re-examined.

Besides high positive degree, we found that 36 essential proteins form a cluster with only positive interactions between them. Perhaps the result of the decision trees was driven by this essential cluster. The authors of [@Zotenko2008a] discovered that essential proteins tend to cluster together and that this behavior is due to their function in complexes. The result that these interactions are activation interactions is revealed in the signed protein network of \textit{D.melanogaster} which is the first of its kind. Also the creators of the signed network [@Vinayagam2014b] and [@Lin2013a] have found that positive interactions are mostly found between proteins of the same complexes and negative interactions between proteins of different complexes. We also found that the essential cluster is reducible, and we reconstructed the network with its irreducible components. This result indicates that information flow is directed which decomposes the essential cluster in 3 parts, input, processing and output. Further analysis must be done to decipher the biological implications of this finding. In order to study further the essential cluster we enriched its proteins with terms of the biological process component of gene ontology. We found 4 types of processes but mostly the proteins participate in the proteasome and in the ATP biosynthesis. So there are activation interactions between essential proteins of these processes which indicates that the essential cluster is neither a component of a specific process nor a single protein complex. In spite of these previous findings, we ought to be careful because the positive interactions between essential proteins maybe because of bias, focus on specific proteins [@Edwards2011], and missing interactions. 

Nevertheless, we want to point that a lot of important theoretical work has recognized the positive - activation interactions for the emergence of self-organization [@Corning1995]. In theoretical network population models, with activation-inhibition interactions, it has been observed that natural selection favors positive interactions [@Mehrotra2009; @Jain2001]. Also using a more abstract model, the hyper-cycles, Eigen [@M1971] suggested that cooperation was an essential step toward the emergence of complex and self-organized chemical systems [@Sole2011a]. And since essential genes are more conserved than nonessential [@Koonin2003; @Mushegian1996] there might be an evolutionary explanation of their positive interactions. The connection of the essential cluster and the aforementioned theoretical work is very vague at the moment and more investigation is needed.

Although prediction of essentiality focuses on individual proteins, the work of [@Hart2007] suggested that essentiality isn't a protein property. They indicated that protein essentiality is a byproduct of protein complex essentiality. This means that the lethality of the organism after the disruption of a protein is due to the malfunction of a complex that this proteins participates in. In 2013, [@Ryan2013b] referred to this hypothesis as \textit{"All or Nothing"} which means that a complex will either contain mostly nonessential proteins or mostly essential proteins. They tested this by bootstrapping the proteins of complexes to create a null distribution of essentiality fraction (equation \ref{essential_fr}). Their tests were performed on unicellular organisms. We followed their methodology for \textit{D.melanogaster's} complexes and found similar results (Figure \ref{complex_modular}). Specifically we found that in \textit{D.melanogaster} there is only one complex with essentiality fraction above $0.8$ which led to slightly different result. There are more complexes than expected with essentiality fraction in the intervals $[0,0.2]$ and $(0.6,0.8]$. In the other intervals the observed complexes are less than expected, also all the results were substantial (Figure \ref{cumulative_complex_essen}). In our analysis, we used $\approx 4$ times more complexes that the previous studies which might be the reason of the slightly weaker results. The \textit{"All or Nothing"} hypothesis should be rechecked when more reliable and rich data about complexes appear. Because at the moment identifying complexes, both experimentally and computationally\footnote{During the analysis we discovered a bias towards small sized complexes in the COMPLEAT database (see Appendix \ref{append_compleat})}, remains a huge challenge [@Hartwell1999a; @Koch2012].

In this work, we used centralities for the evaluation of the centrality - lethality rule in the signed PPI of \textit{D.melanogaster}. Signed protein interaction networks are more relevant biologically because they contain activation - inhibition information which is a big step towards the understanding of cellular processes [@Mitra2013a; @Ward2013]. In the future, it is important that more signed physical interaction networks will be constructed for other organisms (for example \textit{S.cerevisiae}). With signed networks also comes the need to generalize the tools to analyse them in order to incorporate signs. For example, we found that positive weighted degree was an important predictor of essential proteins but more complex centralities like betweenness and closeness can't use signed weights. Another challenge is to detect experimentally the temporal nature of physical interactions in the cell [@Gavin2011] and predict this dynamic behavior with the use of temporal networks [@Holme2012]. The temporal activation of protein interactions is due to spatial effects because proteins function in specific locations in the cell [@Aebersold2016a] and because of the differential nature of interactions. It is a fact that different environmental conditions lead to radically different processes in organisms and consequently in different network interactions [@Ideker2012a]. Another challenge is to decipher the modular function of proteins because it has been discovered that proteins function by forming complexes [@Hartwell1999a]. This finding adds a new scale of interactions, interactions between complexes, which creates a need for experimental advances as well as new network analysis tools to handle different network scales [@Koch2012; @Coronges2016]. To conclude, as new data become avalaible that are more reliable and more diverse and this progress is accompaned with the advancement of mathematical and computational tools it will be more clear to decifer the essential components and interactions of organisms and processes. 
